# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{friendly}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Golick"]
  s.date = %q{2009-12-10}
  s.description = %q{}
  s.email = %q{james@giraffesoft.ca}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "APACHE-LICENSE",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "friendly.gemspec",
     "lib/friendly.rb",
     "lib/friendly/attribute.rb",
     "lib/friendly/config.rb",
     "lib/friendly/data_store.rb",
     "lib/friendly/document.rb",
     "lib/friendly/document_table.rb",
     "lib/friendly/index.rb",
     "lib/friendly/query.rb",
     "lib/friendly/storage_proxy.rb",
     "lib/friendly/table.rb",
     "lib/friendly/time.rb",
     "lib/friendly/translator.rb",
     "lib/friendly/uuid.rb",
     "spec/fakes/data_store_fake.rb",
     "spec/fakes/database_fake.rb",
     "spec/fakes/dataset_fake.rb",
     "spec/fakes/document.rb",
     "spec/fakes/serializer_fake.rb",
     "spec/fakes/time_fake.rb",
     "spec/integration/basic_object_lifecycle_spec.rb",
     "spec/integration/batch_insertion_spec.rb",
     "spec/integration/finder_spec.rb",
     "spec/integration/index_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/attribute_spec.rb",
     "spec/unit/config_spec.rb",
     "spec/unit/data_store_spec.rb",
     "spec/unit/document_spec.rb",
     "spec/unit/document_table_spec.rb",
     "spec/unit/index_spec.rb",
     "spec/unit/query_spec.rb",
     "spec/unit/storage_proxy_spec.rb",
     "spec/unit/translator_spec.rb"
  ]
  s.homepage = %q{http://github.com/giraffesoft/friendly}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{}
  s.test_files = [
    "spec/fakes/data_store_fake.rb",
     "spec/fakes/database_fake.rb",
     "spec/fakes/dataset_fake.rb",
     "spec/fakes/document.rb",
     "spec/fakes/serializer_fake.rb",
     "spec/fakes/time_fake.rb",
     "spec/integration/basic_object_lifecycle_spec.rb",
     "spec/integration/batch_insertion_spec.rb",
     "spec/integration/finder_spec.rb",
     "spec/integration/index_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/attribute_spec.rb",
     "spec/unit/config_spec.rb",
     "spec/unit/data_store_spec.rb",
     "spec/unit/document_spec.rb",
     "spec/unit/document_table_spec.rb",
     "spec/unit/index_spec.rb",
     "spec/unit/query_spec.rb",
     "spec/unit/storage_proxy_spec.rb",
     "spec/unit/translator_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<jferris-mocha>, [">= 0"])
      s.add_runtime_dependency(%q<sequel>, [">= 3.7.0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<jferris-mocha>, [">= 0"])
      s.add_dependency(%q<sequel>, [">= 3.7.0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<jferris-mocha>, [">= 0"])
    s.add_dependency(%q<sequel>, [">= 3.7.0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

